version: "2"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - godot
    - staticcheck
  disable:
    - revive

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: "line-length-limit"
    - linters:
        - revive
      text: "nested-structs"
