package messages

// UserMessage represents a message from the user to Claude.
//
// Content can be either a simple string (StringContent) or
// structured blocks (BlockListContent). ParentToolUseID links
// this message to a specific tool use in agent workflows.
type UserMessage struct {
	// Content is the message payload
	Content MessageContent `json:"content"`

	// ParentToolUseID links to a tool use in agent workflows
	ParentToolUseID *string `json:"parent_tool_use_id,omitempty"`

	// IsSynthetic indicates if this message was
	// generated by the SDK
	IsSynthetic bool `json:"isSynthetic,omitempty"`
}

// message implements the Message interface.
func (UserMessage) message() {}
