name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@2fd3724578c33f9f62507d651600d52b8de3c0b9
      - name: Run tests
        run: nix develop -c go test -v -race -coverprofile=coverage.out ./...
      - name: Run builds
        run: nix develop -c go build ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
